name: Bazel Workflow

on:
  workflow_call:
    inputs:
      repo_path:
        required: true
        type: string
      targets:
        required: true
        type: string
      flags:
        required: false
        type: string
        default: ""
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v2
      
      - name: Build Artifacts
        env:
          # REPO_PATH: ${{ inputs.repo_path }}
          # TARGETS: ${{ inputs.targets }}
          # FLAGS: ${{ inputs.flags }}
        run: | 
          set -euo pipefail

          mkdir binaries

          cd ./${{ inputs.repo_path }}
          bazel build "${{ inputs.flags }}" "${{ inputs.targets }}"
          
          for TARGET in $TARGETS: do
            CD_PATH = ${TARGET%:*}
            CD_PATH = ${CD_PATH////}
            BINARY_NAME = ${test#*:}

            cp bazel-bin/CD_PATH/BINARY_NAME ./binaries

      - name: 'Upload binaries'
        uses: actions/upload-artifact@v3
        with:
            name: binaries
            path: ./binaries #path/to/artifact
                    
       
