name: Echo Test

on: [workflow_call]

inputs:
  who-to-greet:  # id of input
      description: 'Who to greet'
      required: true
      default: 'World'

jobs:
  greet:
    runs-on: ubuntu-latest
    env:
      GREET: ${{ inputs.who-to-greet }}
    shell: bash
    steps:
      - run: echo Hello $GREET
      
# runs:
#   using: "composite"
#   steps:
#     - name: Echo
#       shell: bash
#       run: echo Hello ${{ inputs.who-to-greet }}
